CREATE SCHEMA BANK;

CREATE TABLE BANK.ACCOUNT( ACCOUNT_NUMBER BIGINT NOT NULL PRIMARY KEY,
	ACCOUNT_NAME VARCHAR(250) NOT NULL, 
	PIN INT NOT NULL,
        EXPIRATION_DATE DATE NOT NULL,
        BEGIN_DATE DATE NOT NULL,
        STOLEN BOOLEAN NOT NULL,
        BLOCK BOOLEAN NOT NULL,
        DAILYLIMIT DOUBLE NOT NULL
	);

CREATE TABLE BANK.BILL( BILL_NUMBER BIGINT NOT NULL,
        ACCOUNT_NUMBER BIGINT references BANK.ACCOUNT(ACCOUNT_NUMBER),	
        BALANCE DOUBLE NOT NULL,
        TYPES_BILL VARCHAR(32) CONSTRAINT TYPES_BILL_CK CHECK (TYPES_BILL IN ('CHECK','SAVING'))  NOT NULL,
        CONSTRAINT BILL_PK PRIMARY KEY (BILL_NUMBER, TYPES_BILL)
	);
	


CREATE TABLE BANK.TRANSACTION_DETAILS( ACCOUNT_NUMBER BIGINT NOT NULL,
	TRANSACTION_TIME TIMESTAMP NOT NULL,
	TRANSACTION_AMOUNT DOUBLE NOT NULL,
        TYPES_OPERATION VARCHAR(32) CONSTRAINT TYPES_OPERATION_CK CHECK (TYPES_OPERATION IN ('WITHDRAWAL','REFIL')) NOT NULL,
        TYPES_BILL VARCHAR(32) CONSTRAINT TYPES_BILL_TRANS_CK CHECK (TYPES_BILL IN ('CHECK','SAVING')) NOT NULL,
        CONSTRAINT PEOPLE_PK PRIMARY KEY (ACCOUNT_NUMBER, TRANSACTION_TIME)
	);